command_timeout = 2000

[git_branch]
symbol = '🌱 '

[container]
disabled = true

[custom.fof]
# stderr version number print
command = "echo $(gforth --version 2>&1 | grep ^gforth | awk '{ print $2 }')"
description = 'forth source code'
symbol = '4ᵀᴴ '
style = 'bold cyan'
detect_extensions = ['4th'] # filters *.4th files

[custom.sh]
command = "echo $(ls *.sh)"
description = 'shell scripts'
symbol = './ '
style = 'bold green'
detect_extensions = ['sh'] # filters *.sh files

[custom.duino]
description = 'platformio source code'
symbol = 'PlatformIO '
style = 'bold blue'
detect_files = ['platformio.ini'] # filter files
